### ISSUE TITLE
Compile error - module 'esphome.components.climate' has no attribute 'climate_schema'

### ISSUE THREAD

**Issue by dpmworld** [echavet/MitsubishiCN105ESPHome#319]
I receive a complile error while trying to update the configuration:

```INFO ESPHome 2025.3.3
INFO Reading configuration /config/msz-hj25.yaml...
ERROR Unable to load component cn105.climate:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 181, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/.esphome/external_components/87f4d98f/components/cn105/climate.py", line 207, in <module>
    CONFIG_SCHEMA = climate.climate_schema(CN105Climate).extend(
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'esphome.components.climate' has no attribute 'climate_schema'
```

I'm working with ESPHome 2025.3.3, it previously compliled properly....

**Comment by dpmworld** [comment]
My fault! it looks like it is compiling properly with the latest ESPHome 2025.5.2.
