### ISSUE TITLE
Fails to compile with ESPHome 2026.1

### ISSUE THREAD

**Issue by sigmabeta** [echavet/MitsubishiCN105ESPHome#549]
When trying to deploy, it fails with this error:

```
Compiling .pioenvs/living-room-mitsubishi/src/esphome/components/number/number_call.cpp.o
src/esphome/components/cn105/hp_writings.cpp: In member function 'void esphome::CN105Climate::publishWantedRunStatesStateToHA()':
src/esphome/components/cn105/hp_writings.cpp:313:75: error: cannot convert 'esphome::StringRef' to 'const char*'
  313 |         if (this->hasChanged(this->airflow_control_select_->current_option(), this->wantedRunStates.airflow_control, "select airflow control")) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                           |
      |                                                                           esphome::StringRef
In file included from src/esphome/components/cn105/hp_writings.cpp:1:
src/esphome/components/cn105/cn105.h:133:37: note:   initializing argument 1 of 'bool esphome::CN105Climate::hasChanged(const char*, const char*, const char*, bool)'
  133 |         bool hasChanged(const char* before, const char* now, const char* field, bool checkNotNull = false);
      |                         ~~~~~~~~~~~~^~~~~~
Compiling .pioenvs/living-room-mitsubishi/src/esphome/components/number/number_traits.cpp.o
src/esphome/components/cn105/hp_readings.cpp: In member function 'void esphome::CN105Climate::updateExtraSelectComponents(heatpumpSettings&)':
src/esphome/components/cn105/hp_readings.cpp:680:73: error: cannot convert 'esphome::StringRef' to 'const char*'
  680 |         if (this->hasChanged(this->vertical_vane_select_->current_option(), settings.vane, "select vane")) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                         |
      |                                                                         esphome::StringRef
In file included from src/esphome/components/cn105/hp_readings.cpp:1:
src/esphome/components/cn105/cn105.h:133:37: note:   initializing argument 1 of 'bool esphome::CN105Climate::hasChanged(const char*, const char*, const char*, bool)'
  133 |         bool hasChanged(const char* before, const char* now, const char* field, bool checkNotNull = false);
      |                         ~~~~~~~~~~~~^~~~~~
src/esphome/components/cn105/hp_readings.cpp:686:75: error: cannot convert 'esphome::StringRef' to 'const char*'
  686 |         if (this->hasChanged(this->horizontal_vane_select_->current_option(), settings.wideVane, "select wideVane")) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                           |
      |                                                                           esphome::StringRef
src/esphome/components/cn105/cn105.h:133:37: note:   initializing argument 1 of 'bool esphome::CN105Climate::hasChanged(const char*, const char*, const char*, bool)'
  133 |         bool hasChanged(const char* before, const char* now, const char* field, bool checkNotNull = false);
      |                         ~~~~~~~~~~~~^~~~~~
src/esphome/components/cn105/hardware_setting_select.cpp: In member function 'void esphome::HardwareSettingSelect::update_state_from_value(int)':
src/esphome/components/cn105/hardware_setting_select.cpp:35:43: error: cannot convert 'esphome::StringRef' to 'const char*' in assignment
   35 |             cur_opt = this->current_option();
      |                       ~~~~~~~~~~~~~~~~~~~~^~
      |                                           |
      |                                           esphome::StringRef
Compiling .pioenvs/living-room-mitsubishi/src/esphome/components/ota/ota_backend.cpp.o
Compiling .pioenvs/living-room-mitsubishi/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
*** [.pioenvs/living-room-mitsubishi/src/esphome/components/cn105/hp_writings.cpp.o] Error 1
*** [.pioenvs/living-room-mitsubishi/src/esphome/components/cn105/hp_readings.cpp.o] Error 1
*** [.pioenvs/living-room-mitsubishi/src/esphome/components/cn105/hardware_setting_select.cpp.o] Error 1```
