### PR TITLE
Fix build with ESPHome 2026.1+ (Select::current_option() API change)

### PR DESCRIPTION
**Pull request by GioMez**
This PR fixes compilation errors with ESPHome 2026.1+, caused by a breaking change in the `Select::current_option()` API:

< 2025.11: no `current_option()`, fallback to `.state`

2025.11 and 2025.12: `current_option()` returns const `char*`

2026.1+: `current_option()` returns `StringRef`

The patch introduces minimal, version-guarded changes to correctly handle all three cases, keeping full backward compatibility while restoring successful builds on latest ESPHome. Tested with 2026.1 and 2025.12.5

The changes are as small and localized as possible to avoid altering existing behavior or structure.
Please feel free to refactor or reshape this solution if you prefer a cleaner or more maintainable approach, this is meant as a minimal compatibility fix rather than a design statement.

Let's hope there will be no more breaking changes for a while on the ESPHome side 🤞

Thanks a lot for the project and for your time reviewing this!

### CODE REVIEW

**Comment by NosNL** [comment]
Good job, thank you for your effort and for sharing the code!
