### ISSUE TITLE
Compile errors with ESPHome 2026.1.0

### ISSUE THREAD

**Issue by tfvlrue** [echavet/MitsubishiCN105ESPHome#545]
Hi,
I just updated to the latest release of ESPHome and am no longer able to compile this component. I last had this working with ESPHome 2025.11.1, so I'm not sure exactly which version introduced the problem.

Here is the output log, there seem to be some string conversion problems:

```
INFO ESPHome 2026.1.0
INFO Reading configuration /config/esphome/mitsubishi.yaml...
INFO Detected timezone 'America/New_York'
INFO Generating C++ source...
INFO Compiling app... Build path: /data/build/mitsubishi
Processing mitsubishi (board: d1_mini; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
ESPHome: Excluding Updater.cpp from build (using native OTA backend)
ESPHome: Excluding core_esp8266_waveform_phase.cpp from build (waveform not required)
ESPHome: Excluding core_esp8266_waveform_pwm.cpp from build (waveform not required)
Dependency Graph
|-- ESPAsyncTCP @ 2.0.0
|-- ESP8266WiFi @ 1.0
|-- ESPAsyncWebServer @ 3.7.10
|-- DNSServer @ 1.1.1
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.10
|-- ArduinoJson @ 7.4.2
|-- Improv @ 1.2.4
Compiling .pioenvs/mitsubishi/src/esphome/components/cn105/hardware_setting_select.cpp.o
Compiling .pioenvs/mitsubishi/src/esphome/components/cn105/hp_readings.cpp.o
src/esphome/components/cn105/hardware_setting_select.cpp: In member function 'void esphome::HardwareSettingSelect::update_state_from_value(int)':
src/esphome/components/cn105/hardware_setting_select.cpp:35:43: error: cannot convert 'esphome::StringRef' to 'const char*' in assignment
   35 |             cur_opt = this->current_option();
      |                       ~~~~~~~~~~~~~~~~~~~~^~
      |                                           |
      |                                           esphome::StringRef
src/esphome/components/cn105/hp_readings.cpp: In member function 'void esphome::CN105Climate::updateExtraSelectComponents(heatpumpSettings&)':
src/esphome/components/cn105/hp_readings.cpp:680:73: error: cannot convert 'esphome::StringRef' to 'const char*'
  680 |         if (this->hasChanged(this->vertical_vane_select_->current_option(), settings.vane, "select vane")) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                         |
      |                                                                         esphome::StringRef
In file included from src/esphome/components/cn105/hp_readings.cpp:1:
src/esphome/components/cn105/cn105.h:133:37: note:   initializing argument 1 of 'bool esphome::CN105Climate::hasChanged(const char*, const char*, const char*, bool)'
  133 |         bool hasChanged(const char* before, const char* now, const char* field, bool checkNotNull = false);
      |                         ~~~~~~~~~~~~^~~~~~
src/esphome/components/cn105/hp_readings.cpp:686:75: error: cannot convert 'esphome::StringRef' to 'const char*'
  686 |         if (this->hasChanged(this->horizontal_vane_select_->current_option(), settings.wideVane, "select wideVane")) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                           |
      |                                                                           esphome::StringRef
In file included from src/esphome/components/cn105/hp_readings.cpp:1:
src/esphome/components/cn105/cn105.h:133:37: note:   initializing argument 1 of 'bool esphome::CN105Climate::hasChanged(const char*, const char*, const char*, bool)'
  133 |         bool hasChanged(const char* before, const char* now, const char* field, bool checkNotNull = false);
      |                         ~~~~~~~~~~~~^~~~~~
*** [.pioenvs/mitsubishi/src/esphome/components/cn105/hp_readings.cpp.o] Error 1
*** [.pioenvs/mitsubishi/src/esphome/components/cn105/hardware_setting_select.cpp.o] Error 1
========================== [FAILED] Took 6.62 seconds ==========================
```

Let me know if I can provide additional info or debugging. Thanks.
